### ISSUE TITLE
Support of tds_version 7.4

### ISSUE THREAD

**Issue by Loriowar** [tds-fdw/tds_fdw#100]
Is any plans for support tds version 7.4? As I understand from source code, for now fdw has support of versions up to 7.3. Question is related with floating error "20017 Unexpected EOF from the server". Most probably this appears in case of working with MSSQL 2012 and higer using tds version less then 7.4. So, is any plans of supporting last tds version for working with new MSSQL servers?

**Comment by GeoffMontee** [comment]
Hi @Loriowar,

Thanks for the bug report!

The latest commit adds support for TDS version 7.4 when compiled against a version of FreeTDS that supports this version.

**Comment by Loriowar** [comment]
Thanks! Perfectly works with tds_version 7.4 within package [FreeTDS 1.00.9-1](https://launchpad.net/~jamiewillis/+archive/ubuntu/freetds). Error "20017 Unexpected EOF from the server" doesn't appear now.

**Comment by bennawanda** [comment]
Quick question, why can't I be able to insert into? Are there any adjustments I need to make?

**Comment by GeoffMontee** [comment]
Hi @bennawanda,

Write operations are not yet supported by tds_fdw. That feature request is tracked by issue #9.
