### ISSUE TITLE
Implement IMPORT FOREIGN SCHEMA that supports Sybase

### ISSUE THREAD

**Issue by GeoffMontee** [tds-fdw/tds_fdw#104]
Issue #75 is about implementing IMPORT FOREIGN SCHEMA for tds_fdw, but apparently, MS SQL Server and Sybase will require different implementations. The MS SQL Server implementation was covered by pull request #91. So far, the Sybase implementation has not been created.

**Comment by elliotvr** [comment]
Hi,

Nice work, thx @select-artur !!!

But it doesn't work on my (very) old Sybase ASE 12.5, seems like it's stopping right after sending the query 

`SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo'`

Not trying the sysusers table.

I didn't get the difference between EXEC_FAILED and EXEC_FALSE...

And there is a mistake in the query that is getting the schema, after "sc.scale" and before the "FROM", there is a comma.

Thx for the hard work so far !

PS : Sorry for my english, i'm french :-)

**Comment by select-artur** [comment]
Oh, ok. Thank you for testing. I'll investigate it.

**Comment by select-artur** [comment]
Hi,
I created the pull request #110 . I think it should work now :)

**Comment by GeoffMontee** [comment]
This PR was merged a while ago, so I'll go ahead and close this.
