### ISSUE TITLE
timestamp datatype

### ISSUE THREAD

**Issue by GermanGlushkov** [tds-fdw/tds_fdw#106]
Hi, timestamp (aka rowversion) is binary(8), not datetime type in sql server (https://msdn.microsoft.com/en-us/library/ms182776.aspx).
Therefore IMPORT FOREIGN SCHEMA containing timestamp data type fails.
Code should look something like:

/* Date/type types */
else if (strcmp(data_type, "date") == 0)
	appendStringInfoString(&buf, " date");
else if (strcmp(data_type, "datetime") == 0 ||
		 strcmp(data_type, "datetime2") == 0 ||
		 strcmp(data_type, "smalldatetime") == 0)
	appendStringInfo(&buf, " timestamp(%d) without time zone", (datetime_precision > 6) ? 6 : datetime_precision);
else if (strcmp(data_type, "datetimeoffset") == 0)
	appendStringInfo(&buf, " timestamp(%d) with time zone", (datetime_precision > 6) ? 6 : datetime_precision);
else if (strcmp(data_type, "time") == 0)
	appendStringInfoString(&buf, " time");

/* Binary types */
else if (strcmp(data_type, "binary") == 0 ||
	strcmp(data_type, "varbinary") == 0 ||
	strcmp(data_type, "image") == 0)
	appendStringInfoString(&buf, " bytea");

else if (strcmp(data_type, "rowversion") == 0 ||
	strcmp(data_type, "timestamp") == 0)
	appendStringInfoString(&buf, " bytea");

**Comment by GeoffMontee** [comment]
Thanks for the fix! This change has been pushed.

**Comment by Smtgr14** [comment]
Since this has been resolved, can @GeoffMontee or @GermanGlushkov close this issue?
