### ISSUE TITLE
Problem with like fixed

### ISSUE THREAD

**Issue by ale2317** [tds-fdw/tds_fdw#118]
Hy, 

we get a error with this query:

select * from table where colume LIKE "something%" .

I found a similar error on issue  #76 and see you fix that. I have now insert this lines at your deparse.c to fix my Problems: 

```
deparse.c line 1748:

else if (strncmp(opname, "~~", NAMEDATALEN) == 0)
        {
                appendStringInfoString(buf, "LIKE");
        }
        else if (strncmp(opname, "~~*", NAMEDATALEN) == 0)
        {
                appendStringInfoString(buf, "LIKE");
        }
```
Can you please insert this on the master branch.

Regards 

Alex

**Comment by tjkluska** [comment]
Its working for me.
You should send this as poll request.

**Comment by juliogonzalez** [comment]
Closing, since this fix at the first comment was merged.
