### ISSUE TITLE
UUID/GUID not working properly on Ubuntu

### ISSUE THREAD

**Issue by drilus** [tds-fdw/tds_fdw#130]
Does tds-fdw support uuids/guids on Ubuntu?

On Mac OS it works, but on Ubuntu the uuids have all sorts of unicode characters thrown in. I'm guessing it's a configuration issue on my end.

I've tried setting the freetds.conf to use the utf-8 character set but that didn't work. I'm not sure what else to try.

**Comment by GeoffMontee** [comment]
For a type like uuid, I believe that tds_fdw will treat the original data from MS SQL Server/Sybase as text, and then it will try to  do a text->uuid conversion.

Could you please be more specific about what is happening for you? e.g.:

* The original table definition on MS SQL Server/Sybase.
* The original table data from MS SQL Server/Sybase.
* The foreign table definition on PostgreSQL.
* The query you are running in PostgreSQL.
* The data that PostgreSQL sees in its results.
* Your freetds.conf might also be useful.

**Comment by drilus** [comment]
As it turns out I didn't have my freetds.conf file correct. I just needed to set the freetds version. Thanks for the help. Glad it was something simple.
