### ISSUE TITLE
Unistalling the tds_fdw (2.0.0--alpha) and upgrading to another version(1.0.8)

### ISSUE THREAD

**Issue by devendra857** [tds-fdw/tds_fdw#132]
How can i unistall the source code which i have installed and change it to tds_fdw 1.0.8 ?  I have installed tds_fdw 2.0.0--alpha but i want to uninstall it and install another version of it.

**Comment by juliogonzalez** [comment]
What do you mean with "uninstall the source code which i have installed"?

Do you mean removing the extension from your PostgreSQL databases, and then removing the binaries?

**Comment by Smtgr14** [comment]
It should be safe to simply DROP EXTENSION and make install the version you want. Your install may be a little dirty, but it should not cause issues.

**Comment by TheRevenantStar** [comment]
@GeoffMontee can we close this one too? It seems to have been abandoned.

**Comment by GeoffMontee** [comment]
Sure, I can close it. Thanks, @TheRevenantStar.
