### ISSUE TITLE
FEATURE REQUEST:  Extend Import Foreign Schema to Views 

### ISSUE THREAD

**Issue by bradleyf** [tds-fdw/tds_fdw#178]
Looking at the source code, importing foreign schema is limited to Tables only.  Please extend it to work with Views as well.   Thank you!

**Comment by wesselmdw** [comment]
I would find this feature very useful

**Comment by DrLove73** [comment]
It is possible to get all info about columns from MSSQL Views using following query:
```
SELECT s.name as schema_name
       ,o.name as table_or_view_name
       ,c.column_id
	   ,c.name as column_name
       ,t.name as data_type
       ,c.max_length
       ,c.precision
       ,c.scale
       /* start of not necessary columns */
       ,c.system_type_id
       ,c.user_type_id
       ,c.collation_name
       ,c.is_nullable
       ,c.is_ansi_padded
       ,c.is_rowguidcol
       ,c.is_identity
       ,c.is_computed
       ,c.is_filestream
       ,c.is_replicated
       ,c.is_non_sql_subscribed
       ,c.is_merge_published
       ,c.is_dts_replicated
       ,c.is_xml_document
       ,c.xml_collection_id
       ,c.default_object_id
       ,c.rule_object_id
       ,c.is_sparse
       ,c.is_column_set
       /* end of not necessary columns */
       ,o.object_id
       ,o.schema_id
       ,o.type
       
FROM   sys.columns c
       JOIN sys.types t
         ON t.user_type_id = c.user_type_id
            AND t.system_type_id = c.system_type_id
       JOIN sys.objects o
         ON o.object_id = c.object_id
       JOIN sys.schemas s
         ON o.schema_id = s.schema_id
WHERE (s.name = 'izp') AND (o.type = 'V')
/* WHERE (s.name = 'izp') AND (o.type = 'U') for tables */
/* WHERE (s.name = 'izp') AND (o.type = 'V') for views */
/* WHERE s.name = 'izp' filter by schema name*/
/* WHERE  object_id = OBJECT_ID('PaymentSchedule_vw') */
ORDER BY o.type DESC, o.schema_id, o.name, c.column_id
```
I have not looked at the code, but I am guessing tds_fdw could add "option" to switch adding views on/off and using provided data about columns to generate appropriate foreign tables (with "view_" prefix).

**Comment by DrLove73** [comment]
Here is resultant info about one of my views:

<table cellpadding="2" cellspacing="0">
	<tr>
		<td height="17" style="border: none; padding: 0mm">
			<p align="left">schema_name</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">table_or_view_name</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">column_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">column_name</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">data_type</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">max_length</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">precision</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">scale</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">system_type_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">user_type_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">collation_name</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_nullable</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_ansi_padded</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_rowguidcol</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_identity</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_computed</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_filestream</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_replicated</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_non_sql_subscribed</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_merge_published</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_dts_replicated</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_xml_document</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">xml_collection_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">default_object_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">rule_object_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_sparse</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">is_column_set</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">object_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">schema_id</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">type</p>
		</td>
	</tr>
	<tr>
		<td height="17" style="border: none; padding: 0mm">
			<p align="left">izp</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">UslugaRacuniSumaNis</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="1" sdnum="9242;">
			<p align="right">1</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">UslugaId1</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">smallint</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="2" sdnum="9242;">
			<p align="right">2</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="5" sdnum="9242;">
			<p align="right">5</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="52" sdnum="9242;">
			<p align="right">52</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="52" sdnum="9242;">
			<p align="right">52</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">NULL</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="1" sdnum="9242;">
			<p align="right">1</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="1719013205" sdnum="9242;">
			<p align="right">1719013205</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="5" sdnum="9242;">
			<p align="right">5</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">V 
			</p>
		</td>
	</tr>
	<tr>
		<td height="17" style="border: none; padding: 0mm">
			<p align="left">izp</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">UslugaRacuniSumaNis</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="2" sdnum="9242;">
			<p align="right">2</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">IznosStavki</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">decimal</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="17" sdnum="9242;">
			<p align="right">17</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="38" sdnum="9242;">
			<p align="right">38</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="2" sdnum="9242;">
			<p align="right">2</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="106" sdnum="9242;">
			<p align="right">106</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="106" sdnum="9242;">
			<p align="right">106</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">NULL</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="1" sdnum="9242;">
			<p align="right">1</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="1719013205" sdnum="9242;">
			<p align="right">1719013205</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="5" sdnum="9242;">
			<p align="right">5</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">V 
			</p>
		</td>
	</tr>
	<tr>
		<td height="17" style="border: none; padding: 0mm">
			<p align="left">izp</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">UslugaRacuniSumaNis</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="3" sdnum="9242;">
			<p align="right">3</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">CountStavki</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">int</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="4" sdnum="9242;">
			<p align="right">4</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="10" sdnum="9242;">
			<p align="right">10</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="56" sdnum="9242;">
			<p align="right">56</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="56" sdnum="9242;">
			<p align="right">56</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">NULL</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="1" sdnum="9242;">
			<p align="right">1</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="0" sdnum="9242;">
			<p align="right">0</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="1719013205" sdnum="9242;">
			<p align="right">1719013205</p>
		</td>
		<td style="border: none; padding: 0mm" sdval="5" sdnum="9242;">
			<p align="right">5</p>
		</td>
		<td style="border: none; padding: 0mm">
			<p align="left">V 
			</p>
		</td>
	</tr>
</table>

**Comment by DrLove73** [comment]
In my case following query is with columns that do not have "0" for every row:

```
SELECT s.name as schema_name
       ,o.name as table_or_view_name
       ,c.column_id
	   ,c.name as column_name
       ,t.name as data_type
       ,c.max_length
       ,c.precision
       ,c.scale
       /* start of not necessary columns */
       ,c.system_type_id
       ,c.user_type_id
       ,c.collation_name
       ,c.is_nullable
       ,c.is_ansi_padded
       /* end of not necessary columns */
       ,o.schema_id
       ,o.type
       
FROM   sys.columns c
       JOIN sys.types t
         ON t.user_type_id = c.user_type_id
            AND t.system_type_id = c.system_type_id
       JOIN sys.objects o
         ON o.object_id = c.object_id
       JOIN sys.schemas s
         ON o.schema_id = s.schema_id
WHERE (s.name = 'izp') AND (o.type = 'V')
/* WHERE (s.name = 'izp') AND (o.type = 'U') for tables */
/* WHERE (s.name = 'izp') AND (o.type = 'V') for views */
/* WHERE s.name = 'izp' filter by schema name*/
/* WHERE  object_id = OBJECT_ID('PaymentSchedule_vw') */
ORDER BY o.type DESC, o.schema_id, o.name, c.column_id
```

**Comment by DrLove73** [comment]
I have partial success with creating FOREIGN TABLES to get data from views.
If I use simple view:
```
CREATE FOREIGN TABLE mssql.view_DuzniciSumaPoRacunuView (	
          "posaoId"	INT
          ,"SumOfukupno"	decimal
)	
SERVER izp2012	
OPTIONS (	
schema_name 	'izp'
, table_name 	'DuzniciSumaPoRacunuView'
, row_estimate_method 'showplan_all');	
```
everything  is fine, I get rows of data.

But, if I use try more complex view:

```
CREATE FOREIGN TABLE mssql.view_AvansniRacuniView (	
		   "racunId"	INT
          ,"broj"	VARCHAR(20)
          ,"tipRacunaId"	SMALLINT
          ,"naziv"	VARCHAR(50)
          ,"dRacun"	DATE
          ,"Expr1"	VARCHAR(20)
          ,"Expr2"	VARCHAR(1000)
          ,"IB"	VARCHAR(20)
)	
SERVER izp2012	
OPTIONS (	
schema_name 	'izp'
, table_name 	'AvansniRacuniView'
, row_estimate_method 'showplan_all');	
```
creation goes well, but when I try to get data via pgAdmin4, I get:
>list index out of range
and Lazarus + ZEOS Table DOES show results but with problems with characters.
I am to investigate this further tomorrow.

**Comment by pgssimon** [comment]
In tds_fdw.c an edit to the following line (line 2996)...
  "WHERE t.table_type = 'BASE TABLE' "
to... 
  "WHERE t.table_type IN ('BASE TABLE', 'VIEW') "

should allow import from views as well as base tables

**Comment by juliogonzalez** [comment]
@pgssimon maybe you can submit a PR?

We should also add a one test for it. In fact two, one to create the stuff at MSSQL, the other to verify that it works on PostgreSQL's end. Don't worry, it's easy :-)

**Comment by cstork** [comment]
In order to include views with `IMPORT FOREIGN SCHEMA` you also have to change the following line in function `tdsImportSybaseSchema(..)`:

`"WHERE so.type = 'U' AND su.name = ");` to `"WHERE so.type IN ('U','V') AND su.name = ");`.

**Comment by jcarnu** [comment]
IMHO shoudn't we add options to `IMPORT FOREIGN SCHEMA` to include views as suggested @DrLove73  ? It seems a reasonnable thing to do this.
