### ISSUE TITLE
dbuse with Azure 

### ISSUE THREAD

**Issue by johnpaladin** [tds-fdw/tds_fdw#187]
I use dbuse() functions to set the table name on the Azure SQL database, it is connect successfully when I use tsql command. But when use C code to connect it always return fail...

 My C code like below:
     if (  dbuse(dbproc, SQLDBNAME) == FAIL) { 
         exit(1);
     }

 Freetds version 👍 1.00.48.

Very thanks for your reply!

**Comment by GeoffMontee** [comment]
Yeah, this is the same issue i had in issue #23.

This question is not really related to tds_fdw though. For FreeTDS issues, I would suggest posting to the [FreeTDS mailing list](https://lists.ibiblio.org/mailman/listinfo/freetds).
