### ISSUE TITLE
Time to release tds_fdw 2.0.0?

### ISSUE THREAD

**Issue by juliogonzalez** [tds-fdw/tds_fdw#212]
@GeoffMontee I noticed there is more and more people trying `1.0.8` together with PostgreSQL 11 and PostgreSQL 12 (it's on Release Candidate already), and getting troubles.

For example: https://github.com/tds-fdw/tds_fdw/issues/181, https://github.com/tds-fdw/tds_fdw/issues/211 and also https://github.com/NixOS/nixpkgs/pull/66657#issuecomment-521681277 and https://github.com/HSLdevcom/jore-map-ui/issues/970

Also, as tds_fdw `1.0.8` does not build, the RPM is not available at the official PostgreSQL repositories.

I wonder if it's time to release `2.0.0`. Do we have many things broken at the current alpha that were working at `1.0.8`?

**Comment by jcarnu** [comment]
Maybe, it would be a good idea to wait until tds_fdw is PostgreSQL 12 compatible. V12 will be released  on thursday 3rd october and, as many other extensions (i.e. PostGIS) it would be nice if this fdw is V12 compatible.  #211 lists the problems found so far with v12. 

Compilation problem are fixed (I'll post a patch soon) but one function used in tds_fdw was split by Andres Freund for pluggable storage purpose.

I'll try to give a solution asap.

**Comment by GeoffMontee** [comment]
I definitely think it's time to release `2.0.0`. Thanks for initiating this, @juliogonzalez !

I think my original plan was to finish the write support (#9) before I would release tds_fdw 2.0.0. That feature is still unfinished, and it's in the issue9-write branch, but I haven't worked on it in quite a while.

Thanks for the PR #213 , @jcarnu ! 

@juliogonzalez , would it be possible to get PostgreSQL 12 added to the CI?

**Comment by jcarnu** [comment]
@juliogonzalez just in case here is a snippet from another provisionning of mine on centos/7 `${PGVERSION}` is one of my input variable with `12` :

~~~shell
yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG
if [ ${PGVERSION} -eq "12 " ]; then 
    yum-config-manager --enable pgdg12-updates-testing
fi
yum install -y postgresql${PGVERSION} postgresql${PGVERSION}-server postgresql${PGVERSION}-llvmjit postgresql${PGVERSION}-contrib postgresql${PGVERSION}-libs
# PostgreSQL Cluster initialize
/usr/pgsql-${PGVERSION}/bin/postgresql-${PGVERSION}-setup initdb
systemctl enable postgresql-${PGVERSION}
systemctl start postgresql-${PGVERSION}


~~~

**Comment by juliogonzalez** [comment]
Adding PostgreSQL 12 now to all of our OS.

It will take me a while to generate all the required docker images (base, tds_fdw). Will ping you and rerun tests at #213 when everything is ready.

**Comment by juliogonzalez** [comment]
Ooops... the MSSQL schemas can't have hyphen. Fixing that and rerunning.

**Comment by jcarnu** [comment]
This should be ok for pg12 now. I think we can close #211 if this is ok.

**Comment by GeoffMontee** [comment]
We may want to wait on this release until we find out which protocol changes @jcarnu had to make to get `tds_fdw` working with SQL Server 2019.

**Comment by juliogonzalez** [comment]
I agree, let's wait a little bit more.

**Comment by devrimgunduz** [comment]
How much more? :) We need a version for PostgreSQL 12.

**Comment by jcarnu** [comment]
V12 is working, I agree Devrim. 2019 protocol finally is ok also.

There's a task list. I won't be able to help before mid december... But
OTOH, that would be great if packages were available soon. :-)

>

**Comment by GeoffMontee** [comment]
I went ahead and released 2.0.1 as the first stable 2.0 release:

https://github.com/tds-fdw/tds_fdw/releases/tag/v2.0.1

**Comment by juliogonzalez** [comment]
Time to generate the RPMs! :-)

**Comment by juliogonzalez** [comment]
I have a branch now that it's able to generate them, but I think I will need to add CentOS8 support (I added openSUSE/SUSE support with 2.0.1). Will continue working on this during the weekend.

**Comment by devrimgunduz** [comment]
Are you serious? The community PostgreSQL YUM and ZYPP repos already have the RPMs, and people really use that one. Why would you duplicate the effort (which would probably not work with the community RPMs anyway) ?

**Comment by juliogonzalez** [comment]
Can you point me to the zypp repos?

I am aware of the Yum repositories, but last noticed I had from the PostgreSQL devs is that they removed tds_fdw from PostgreSQL newer versions as the stable version 1.0.8 was not working. No idea how much time it will take getting it back.

Besides, PostgreSQL community will only generate the RPMs for PostgreSQL versions they maintain, but distributions are also maintaining versions they don't support, and in that cases it makes sense having the SPECs (right I have specs starting with PostgreSQL 9.3).
