### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by juliogonzalez** [tds-fdw/tds_fdw#215]
If any designers are around, they could help with a PR for [hacktoberfest](https://hacktoberfest.digitalocean.com) with a logo to be used at the [GitHub organization](https://github.com/tds-fdw), [main repository README](https://github.com/tds-fdw/tds_fdw/blob/master/README.md), etc.

No big requirements as long as:

### It allows people to somehow understand what `tds_fdw` is used for

> Connect PostgreSQL to databases that use the Tabular Data Stream (TDS) protocol, such as Sybase databases and Microsoft SQL server.

(the must powerful idea would be to represent PostgreSQL connecting Microsoft SQL server somehow, but something more generic should do it.

Whatever you do, remember to **avoid** any copyright/trademarks infringements.

### We can scale up or scale down

So it can be used as icon for the project, as bigger image at the README, etc. :-)

### License

Anyone, as long as provides:
- The right to use it for any purpose.
- The right to copy it.
- The right to modify it.

Needless to say, there will be attribution, so you can also use this for your portfolio if you want :-)

**Comment by Sabihashaik** [comment]
Hi @juliogonzalez I'd like to give this an attempt! 😄

**Comment by juliogonzalez** [comment]
Go for it @Sabihashaik! :-)

**Comment by juliogonzalez** [comment]
Thanks to @Sabihashaik and @RAFAELDEV2016 we now have a logo.

Closing this issue.
