### ISSUE TITLE
Issue to get the library on postgres 9.6 having pg_config from 11

### ISSUE THREAD

**Issue by detzu** [tds-fdw/tds_fdw#225]
had issues to get the 9.6 library if 11 was installed on the host. Had to change in Makefile
the line

PG_CONFIG = pg_config
to
PG_CONFIG = /usr/lib/postgresql/9.6/bin/pg_config

used version tds_fdw-1.0.8 for this.

**Comment by TheRevenantStar** [comment]
Instead of posting this as an issue, can you submit a pull request?

**Comment by juliogonzalez** [comment]
No need to change the `Makefile`:
```
make PG_CONFIG = /usr/lib/postgresql/9.6/bin/pg_config
```
:-)
