### ISSUE TITLE
Encrypted ssl/tsl connection

### ISSUE THREAD

**Issue by Soni-Harriz** [tds-fdw/tds_fdw#240]
Is tds_fdw support encrypted ssl/tsl connection to MS SQL Server on windows server ?

**Comment by TheRevenantStar** [comment]
tds_fdw uses FreeTDS to make the connections, as such options for FreeTDS deal with encryption.

Set ```encryption = require``` in your freetds.conf
```
[MSSQL]
 host = db.example.com
 port = 1433
 tds version = 7.3
 encryption = require
```

**Comment by juliogonzalez** [comment]
I think this qualifies for a doc PR.
