### ISSUE TITLE
404 Not Found on WGET of v2.0.0-alpha.3.gz

### ISSUE THREAD

**Issue by ZFlyGuy** [tds-fdw/tds_fdw#241]
Hello.

Following the instructions for Ubuntu 18.04, and getting a 404 Not Found on this step:

wget https://github.com/tds-fdw/tds_fdw/archive/${TDS_FDW_VERSION}.gz

Have tried substituting the file name as well, same result, and have tried with 2.0.1 just to see.

**Comment by juliogonzalez** [comment]
It's a typo, it should be `.tar.gz` instead of `.gz`. Can you submit a PR to fix it?

**Comment by ZFlyGuy** [comment]
i dont know if I can create a branch.. ?

**Comment by juliogonzalez** [comment]
You just need to fork the repository, then create a branch on your forked repository, do the changes, commit, push and create a PR :-)

**Comment by ZFlyGuy** [comment]
Should be there now

**Comment by ZFlyGuy** [comment]
hmm.. not showing up

**Comment by ZFlyGuy** [comment]
My repository not visible.. think i need to submit pull request directly from edits to the doc itself, creating a branch in this repository.

**Comment by juliogonzalez** [comment]
No, the doc is part of the repository itself, and therefore it can be edited from a branch on a forked repository.

Have a look at https://help.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by ZFlyGuy** [comment]
Just edited directly and its showing as pull request now.  However when I edited on forked repository it was only showing there as a pull request.  Quite likely I selected something incorrectly when creating request within the forked repository.  Looks okay now though I think here.  Thank you Julio

**Comment by juliogonzalez** [comment]
Ah, right, it's also possible doing that. As I never edit from WebUI, didn't remember about that :-)

PR merged. Thanks for the contribution!
