### ISSUE TITLE
cannot import a view from mssql ?

### ISSUE THREAD

**Issue by suishaojian** [tds-fdw/tds_fdw#247]
I got a view in mssql and I just create a foreign schema in pg with tds_fdw,
but I can just select the table not the view . 
So  I want to know if tds_fdw cannot import view ?
Thank you very much if anyone can offer help.

**Comment by juliogonzalez** [comment]
Duplicates #178 

There's a PR pending since last year (#233) but it's lacking tests. I guess that if the developer doesn't reply I will need to handle it (I am not C developer but can take care of the tests, so if they work, we could merge).

**Comment by suishaojian** [comment]
> Duplicates #178
> 
> There's a PR pending since last year (#233) but it's lacking tests. I guess that if the developer doesn't reply I will need to handle it (I am not C developer but can take care of the tests, so if they work, we could merge).

Thank you so much .
