### ISSUE TITLE
Build failure with PG13: src/deparse.c:1703:23: error: too few arguments to function ‘lnext’

### ISSUE THREAD

**Issue by df7cb** [tds-fdw/tds_fdw#259]
Hi,

Aaron Pavely contributed the packaging of tds_fdw for Debian and apt.postgresql.org, and things look fine for the stable PostgreSQL versions. However, PostgreSQL 13 is already at beta 3, and tds_fdw does not support it:

```
15:39:47 /usr/include/postgresql/13/server/nodes/pg_list.h:321:19: note: expected ‘const List *’ but argument is of type ‘ListCell *’
15:39:47   321 | lnext(const List *l, const ListCell *c)
15:39:47       |       ~~~~~~~~~~~~^
15:39:47 src/deparse.c:1703:23: error: too few arguments to function ‘lnext’
15:39:47  1703 |   if (use_variadic && lnext(arg) == NULL)
15:39:47       |                       ^~~~~
15:39:47 In file included from /usr/include/postgresql/13/server/nodes/primnodes.h:22,
15:39:47                  from /usr/include/postgresql/13/server/access/relation.h:17,
15:39:47                  from /usr/include/postgresql/13/server/access/heapam.h:17,
15:39:47                  from src/deparse.c:54:
15:39:47 /usr/include/postgresql/13/server/nodes/pg_list.h:321:1: note: declared here
15:39:47   321 | lnext(const List *l, const ListCell *c)
15:39:47       | ^~~~~
```

Full build log: https://pgdgbuild.dus.dg-i.net/job/tds-fdw-binaries-beta/1/architecture=amd64,distribution=sid/console

Please consider tagging a new release with PG 13 support so users can upgrade. Thanks :)

**Comment by GeoffMontee** [comment]
Thanks! I'll try to look into this soon.

**Comment by devrimgunduz** [comment]
Hi @GeoffMontee ,

13.0 is out tomorrow. When will you push a new release?

Regards, Devrim

**Comment by GeoffMontee** [comment]
Hi @devrimgunduz, 

I do not have an ETA at the moment. Sorry for the inconvenience.

**Comment by GeoffMontee** [comment]
Pull request #261 from @MThomassen adds support for PostgreSQL 13. I haven't merged it yet, because I would prefer to run out automated tests against PostgreSQL 13 first. I have reached out to @juliogonzalez to ask him to add PostgreSQL 13 to our Jenkins CI.

**Comment by GeoffMontee** [comment]
Hi @df7cb and @devrimgunduz,

Please try to use the 2.0.2 release with PostgreSQL 13:

https://github.com/tds-fdw/tds_fdw/releases/tag/v2.0.2

If you have any additional issues, please let us know.

Thanks!

**Comment by juliogonzalez** [comment]
@GeoffMontee don't you need to bump the version at the following places before releasing?

https://github.com/tds-fdw/tds_fdw/blob/master/META.json#L4
https://github.com/tds-fdw/tds_fdw/blob/master/META.json#L22
https://github.com/tds-fdw/tds_fdw/blob/master/tds_fdw.control#L19

**Comment by GeoffMontee** [comment]
Hi @juliogonzalez, 

Right. Thanks for the reminder!

I just pushed a version bump, and then fixed the v2.0.2 release tag to point to the proper commit.

Thanks!

**Comment by juliogonzalez** [comment]
No problem!

I just noticed when I started generating the RPMs, as `rpm`complained about `tds_fdw--2.0.1.sql` being missing.

**Comment by devrimgunduz** [comment]
Thanks @GeoffMontee ! Pushed packages to the repos.

Regards, Devrim

**Comment by df7cb** [comment]
Debian packages also updated, thanks!
