### ISSUE TITLE
Prepare the CI for Ubuntu 20.04 and CentOS8

### ISSUE THREAD

**Issue by juliogonzalez** [tds-fdw/tds_fdw#265]
Not urgent at all, but we should start slowly preparing this.

Maybe at some point we will want to stop testing CentOS7 and start using CentOS8, or stop testing Ubuntu 18.04 and start testing Ubuntu 20.04, so we have one "old" GNU/Linux Distribution and one newer GNU/Linux Distribution.

**Comment by josemvm** [comment]
hi @juliogonzalez 

thanks for your work!
the tds_fdw latest version works fine with ubuntu server 20.04
