### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by robins** [tds-fdw/tds_fdw#305]
# Issue report

(Not really a bug-report but)... The recentmost release v2.0.2 is ~18 months old, and it misses some important commits such as c179f353f4c20a41aae1bc72d185906c09fb8147, 9432217932faf12204b7b4b061bf3613871910c6 and e705c02ade30e4581589ab664b2962b2d4247185.

It'd be great if there could be a release published that allows end-users to point to a newer version.

Thanks

**Comment by devrimgunduz-edb** [comment]
@GeoffMontee @juliogonzalez 

+1 on this.

Cheers, Devrim

**Comment by GeoffMontee** [comment]
I will try to prepare a new release soon.

Thanks!

**Comment by devrimgunduz** [comment]
Hi @GeoffMontee ,

Any updates?

Cheers, Devrim

**Comment by devrimgunduz-dh** [comment]
ping

**Comment by GeoffMontee** [comment]
Sorry, @devrimgunduz. If anyone would like to submit a PR to bump the version, i created issue #316 with the details of what needs to occur. After the version is bumped in the tree, then I can prepare the release.

If no one wants to submit a PR for this, then I will try to get to this soon.

**Comment by juliogonzalez** [comment]
@GeoffMontee done :-)

**Comment by GeoffMontee** [comment]
Thanks, @juliogonzalez !

tds_fdw 2.0.3 has been released: https://github.com/tds-fdw/tds_fdw/releases/tag/v2.0.3

**Comment by devrimgunduz** [comment]
Thanks!
