### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by aseques** [tds-fdw/tds_fdw#344]
# Issue report

It would be very convenient to do a new release, because the last change commited (https://github.com/tds-fdw/tds_fdw/commit/22ee5d3f46909b35efb2600b44ec19a35179630e) allows for a neat version upgrade instead of having to get the master tag from git.

**Comment by GeoffMontee** [comment]
Thanks! We will try to make a new release soon.

**Comment by cobolbaby** [comment]
+1 wait for the query cancellation.

**Comment by cobolbaby** [comment]
@GeoffMontee 

Does this project have any development plans? It seems like there are many requirements but no further progress has been made.

**Comment by GeoffMontee** [comment]
2.0.4 was just released. Thanks for your patience.
