### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by devrimgunduz** [tds-fdw/tds_fdw#364]
Hi,

2.0.3 fails to build against PostgreSQL 17.  v17 beta2 is already out. Can you please take a look? Thanks! Devrim

[tds-fdw-pg17.txt](https://github.com/user-attachments/files/16415661/tds-fdw-pg17.txt)

**Comment by devrimgunduz** [comment]
Hi @GeoffMontee ,

https://github.com/tds-fdw/tds_fdw/pull/358 fixes v17 issues. Beta3 is already out. Can you please release a new version so that I can build the RPMs?

Thanks!

**Comment by df7cb** [comment]
Debian would also appreciate a new release, thanks!

**Comment by GeoffMontee** [comment]
Hi @devrimgunduz and @df7cb,

This is in progress via PR #367. Thanks for your patience.

**Comment by GeoffMontee** [comment]
Hi @devrimgunduz and @df7cb,

2.0.4 is now available. Please let me know if you run into any issues.

**Comment by devrimgunduz** [comment]
Hi,

I'm seeing some warnings against GCC 14.2. Not sure they are critical or not. Other than that, build works fine:

> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I./include/ -fvisibility=hidden  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o src/deparse.bc src/deparse.c
In file included from /usr/pgsql-17/include/server/postgres.h:46,
                 from src/options.c:4:
src/options.c: In function ‘tdsGetForeignServerOptions’:
src/options.c:326:56: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘int’ [-Wformat=]
  326 |                                                 errmsg("Redundant option: sqlserver_ansi_mode (%s)", defGetBoolean(def))
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~
      |                                                                                                      |
      |                                                                                                      int
/usr/pgsql-17/include/server/utils/elog.h:147:25: note: in definition of macro ‘ereport_domain’
  147 |                         __VA_ARGS__, errfinish(__FILE__, __LINE__, __func__); \
      |                         ^~~~~~~~~~~
src/options.c:324:33: note: in expansion of macro ‘ereport’
  324 |                                 ereport(ERROR,
      |                                 ^~~~~~~
src/options.c:326:97: note: format string is defined here
  326 |                                                 errmsg("Redundant option: sqlserver_ansi_mode (%s)", defGetBoolean(def))
      |                                                                                                ~^
      |                                                                                                 |
      |                                                                                                 char *
      |                                                                                                %d
src/tds_fdw.c: In function ‘tdsIterateForeignScan’:
src/tds_fdw.c:1875:21: warning: declaration of ‘ncol’ shadows a previous local [-Wshadow=compatible-local]
 1875 |                 int ncol;
      |                     ^~~~
src/tds_fdw.c:1686:13: note: shadowed declaration is here
 1686 |         int ncol;
      |             ^~~~
src/tds_fdw.c: In function ‘tdsImportForeignSchema’:
src/tds_fdw.c:3954:24: warning: unused variable ‘buf’ [-Wunused-variable]
 3954 |         StringInfoData buf;
      |                        ^~~
src/tds_fdw.c:3953:25: warning: unused variable ‘is_sql_server’ [-Wunused-variable]
 3953 |         bool            is_sql_server = true;
      |                         ^~~~~~~~~~~~~
In file included from /usr/pgsql-17/include/server/postgres.h:46,
                 from src/tds_fdw.c:32:
src/tds_fdw.c: In function ‘tdsIsSqlServer’:
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:487:33: note: in expansion of macro ‘ereport’
  487 |                                 ereport(ERROR,
      |                                 ^~~~~~~
src/tds_fdw.c:492:25: note: here
  492 |                         case FAIL:
      |                         ^~~~
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:493:33: note: in expansion of macro ‘ereport’
  493 |                                 ereport(ERROR,
      |                                 ^~~~~~~
src/tds_fdw.c:498:25: note: here
  498 |                         default:
      |                         ^~~~~~~
src/tds_fdw.c: In function ‘tdsGetRowCountShowPlanAll’:
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:955:41: note: in expansion of macro ‘ereport’
  955 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:960:33: note: here
  960 |                                 case FAIL:
      |                                 ^~~~
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:961:41: note: in expansion of macro ‘ereport’
  961 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:966:33: note: here
  966 |                                 default:
      |                                 ^~~~~~~
src/tds_fdw.c: In function ‘tdsGetRowCountExecute’:
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:1120:41: note: in expansion of macro ‘ereport’
 1120 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:1125:33: note: here
 1125 |                                 case FAIL:
      |                                 ^~~~
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:1126:41: note: in expansion of macro ‘ereport’
 1126 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:1131:33: note: here
 1131 |                                 default:
      |                                 ^~~~~~~
src/tds_fdw.c: In function ‘tdsConvertToCString’:
src/tds_fdw.c:1314:28: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1314 |                         if (erc == SUCCEED)
      |                            ^
src/tds_fdw.c:1325:17: note: here
 1325 |                 default:
      |                 ^~~~~~~
src/tds_fdw.c: In function ‘tdsImportSqlServerSchema’:
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:3524:41: note: in expansion of macro ‘ereport’
 3524 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:3529:33: note: here
 3529 |                                 case FAIL:
      |                                 ^~~~
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:3530:41: note: in expansion of macro ‘ereport’
 3530 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:3535:33: note: here
 3535 |                                 default:
      |                                 ^~~~~~~
src/tds_fdw.c: In function ‘tdsImportSybaseSchema’:
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:3907:41: note: in expansion of macro ‘ereport’
 3907 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:3912:33: note: here
 3912 |                                 case FAIL:
      |                                 ^~~~
/usr/pgsql-17/include/server/utils/elog.h:142:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  142 |         do { \
      |            ^
/usr/pgsql-17/include/server/utils/elog.h:164:9: note: in expansion of macro ‘ereport_domain’
  164 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
src/tds_fdw.c:3913:41: note: in expansion of macro ‘ereport’
 3913 |                                         ereport(ERROR,
      |                                         ^~~~~~~
src/tds_fdw.c:3918:33: note: here
 3918 |                                 default:
      |                                 ^~~~~~~

**Comment by df7cb** [comment]
Looking good on Debian as well, thanks!
