### ISSUE TITLE
tds_fdw does not compile on postgres 9.5 and freetds

### ISSUE THREAD

**Issue by uherbst** [tds-fdw/tds_fdw#58]
Hi,
we have:
- Oracle Linux 7
- self compiled postgres 9.5 (in /usr/local/postgres/postgres-9.5.0)
- self compiled freetds (in /usr/local/postgres/freetds)

What have we done:
in Makefile we changed: PG_CPPFLAGS := -I/usr/local/postgres/freetds/include -I./include/

Then executed:
PATH=/usr/local/postgres/postgres-9.5.0/bin:$PATH make USE_PGXS=1

Error:
[postgres@d001dadl tds_fdw-1.0.7]$ PATH=/usr/local/postgres/postgres-9.5.0/bin:$PATH make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -shared -o tds_fdw.so src/tds_fdw.o src/options.o -L/usr/local/postgres/postgres-9.5.0/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/postgres/postgres-9.5.0/lib',--enable-new-dtags  -lsybdb 
/bin/ld: cannot find -lsybdb
collect2: error: ld returned 1 exit status
make: *** [tds_fdw.so] Error 1

Where have I to add the right -L/usr/local/postgres/freetds/lib - option ?

**Comment by GeoffMontee** [comment]
Hi @uherbst,

> Where have I to add the right -L/usr/local/postgres/freetds/lib - option ?

I would recommend adding it to either [`SHLIB_LINK`](https://github.com/GeoffMontee/tds_fdw/blob/50fb09222583d073233fbd0af0724dd0268e8548/Makefile#L38) or [`PG_LIBS`](https://github.com/GeoffMontee/tds_fdw/blob/50fb09222583d073233fbd0af0724dd0268e8548/Makefile#L40) in the Makefile.
