### ISSUE TITLE
src/tds_fdw.c:63:22: fatal error: sybfront.h: No such file or directory

### ISSUE THREAD

**Issue by cmodomingo** [tds-fdw/tds_fdw#63]
Hi Geoff,

I'm trying to install the extension with my PostgreSQL 9.3.3 but when I execute the command below the error above is being encountered.

make USE_PGXS=1

Please note that I have already installed the freetds package but I'm still getting this error.

Thank you in advance for your help.

**Comment by GeoffMontee** [comment]
Hi @cmodomingo,

I would need more information to help, including what OS you are using, and what packages you have installed.

The `freetds` package alone is not enough to compile `tds_fdw`. For Ubuntu, [look here](https://github.com/GeoffMontee/tds_fdw/blob/master/InstallUbuntu.md#install-freetds) for the package list. For CentOS/Red Hat, [look here](https://github.com/GeoffMontee/tds_fdw/blob/master/InstallCentOS.md#install-freetds).

As an example, you might see this error on CentOS if you have the `freetds` package installed, but you are missing the `freetds-devel` package.

**Comment by cmodomingo** [comment]
Hi Geoff,

We are using RHEL 7. Prior the freedts installation I cannot locate sybfront.h but after the installation I can already locate it with this, do I still need to install the freedts-devel?

Thank you in advance :)

**Comment by GeoffMontee** [comment]
Can you please provide the output of the following?

```
rpm -qa | grep -i "freetds"
rpm -ql freetds
rpm -ql freetds-devel
```

**Comment by cmodomingo** [comment]
## Hi Geoff,

### I installed the freetds package from source. Please see below steps that I took to install the package:

wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.95.87.tar.gz
--2016-03-09 13:06:18--  ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.95.87.tar.gz
           => freetds-0.95.87.tar.gz
Resolving ftp.freetds.org (ftp.freetds.org)... 38.117.134.18
Connecting to ftp.freetds.org (ftp.freetds.org)|38.117.134.18|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/freetds/stable ... done.
==> SIZE freetds-0.95.87.tar.gz ... 4546910
==> PASV ... done.    ==> RETR freetds-0.95.87.tar.gz ... done.
Length: 4546910 (4.3M) (unauthoritative)

100%[==============================================================================================================================>] 4,546,910   3.15MB/s   in 1.4s

2016-03-09 13:06:20 (3.15 MB/s) - freetds-0.95.87.tar.gz saved [4546910]

gunzip freetds-0.95.87.tar.gz
tar xvf freetds-0.95.87.tar
cd freetds-0.95.87
./configure --prefix=/pgsql/g01/software/rdbms/9.3.3/ --disable-libiconv --disable-odbc --disable-apps --disable-server --disable-pool
make
make install

### Then I follow these steps to install tds_fdw:

wget https://github.com/GeoffMontee/tds_fdw/archive/v1.0.7.tar.gz
--2016-03-09 13:14:17--  https://github.com/GeoffMontee/tds_fdw/archive/v1.0.7.tar.gz
Resolving github.com (github.com)... 192.30.252.131
Connecting to github.com (github.com)|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/GeoffMontee/tds_fdw/tar.gz/v1.0.7 [following]
--2016-03-09 13:14:17--  https://codeload.github.com/GeoffMontee/tds_fdw/tar.gz/v1.0.7
Resolving codeload.github.com (codeload.github.com)... 192.30.252.163
Connecting to codeload.github.com (codeload.github.com)|192.30.252.163|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22290 (22K) [application/x-gzip]
Saving to: v1.0.7.tar.gz

100%[==============================================================================================================================>] 22,290      --.-K/s   in 0.1s

2016-03-09 13:14:18 (163 KB/s) - v1.0.7.tar.gz saved [22290/22290]

gunzip v1.0.7.tar.gz
tar xvf v1.0.7.tar
cd tds_fdw-1.0.7/
make USE_PGXS=1
gcc -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fpic -I./include/ -I. -I. -I/pgsql/g01/software/rdbms/9.3.3/include/server -I/pgsql/g01/software/rdbms/9.3.3/include/internal -D_GNU_SOURCE   -c -o src/tds_fdw.o src/tds_fdw.c
src/tds_fdw.c:63:22: fatal error: sybfront.h: No such file or directory
 #include <sybfront.h>
                      ^
compilation terminated.
make: *** [src/tds_fdw.o] Error 1

### Below is the result whenever I try to locate sybfront.h

locate sybfront.h
/pgsql/g01/software/rdbms/9.3.3/include/sybfront.h
/pgsql/g01/software/rdbms/9.3.3/share/contrib/freetds-0.95.87/include/sybfront.h


## Hope this helps. Thank you!

**Comment by GeoffMontee** [comment]
Ah, I see.

If you are using non-standard include paths for FreeTDS, then you need to tell the compiler where to find the include files. To do this, edit [PG_CPPFLAGS in the tds_fdw Makefile](https://github.com/GeoffMontee/tds_fdw/blob/master/Makefile#L39). For example:

```
PG_CPPFLAGS := -I./include/ -I/pgsql/g01/software/rdbms/9.3.3/include/
```

You may also need to tell the linker where to find the shared libraries by editing either `SHLIB_LINK` or `PG_LIBS` in the Makefile. For example, if your library is at `/pgsql/g01/software/rdbms/9.3.3/lib/`, then you might need something like this:

```
SHLIB_LINK := -lsybdb -L/pgsql/g01/software/rdbms/9.3.3/lib/ -Wl,-rpath,/pgsql/g01/software/rdbms/9.3.3/lib/
```

**Comment by cmodomingo** [comment]
Hi Geoff,

I will try these steps and will keep you posted on my progress.

Thank you :) I really do appreciate your help on this.

**Comment by cmodomingo** [comment]
Hi Geoff,

I'm able to install tds_fdw now. Thank you for your help on this I really do appreciate it. Anyway, I'm just wondering if creating a soft link will also resolve this?

**Comment by GeoffMontee** [comment]
No problem! I'm glad that you were able to get it installed.

Those soft links may or may not fix the problem. I think that would depend on whether those FreeTDS header files include other FreeTDS headers, and how they are included. Personally, I would recommend that you just modify `PG_CPPFLAGS`.

**Comment by mowaiskhan** [comment]
In my build script I work around the problem like this.

PREFIX=Location where you have FreeTDS is installed
awk -v mytext=" -I$PREFIX/sqlserver/include" '/^PG_CPPFLAGS/ {$0=$0mytext} 1' Makefile > t
awk -v mytext=" -L$PREFIX/sqlserver/lib" '/^SHLIB_LINK/ {$0=$0mytext} 1' t > Makefile
