### ISSUE TITLE
9.1, 9.2, 9.3 and 9.4 broken on Ubuntu 12.04 and Centos6 after commit d1e8f10

### ISSUE THREAD

**Issue by juliogonzalez** [tds-fdw/tds_fdw#64]
It seems that the CI is not able to compile for Postgres < 9.5 on ubuntu 12.04 after the last commit  d1e8f10

Ubuntu:
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/147/PG_VER=9.1,label=ubuntu12.04/console
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/147/PG_VER=9.2,label=ubuntu12.04/console
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/147/PG_VER=9.3,label=ubuntu12.04/console
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/147/PG_VER=9.4,label=ubuntu12.04/console

Centos:
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/PG_VER=9.1,label=centos6/147/console
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/PG_VER=9.2,label=centos6/147/console
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/PG_VER=9.3,label=centos6/147/console
https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/PG_VER=9.4,label=centos6/147/console

9.5 is failed for centos and ubuntu, but because connectivity problem during the tests.

**Comment by juliogonzalez** [comment]
Sorry @GeoffMontee, didn't notice the commit at #20

**Comment by GeoffMontee** [comment]
Thanks, @juliogonzalez!

My port of WHERE clause and column pushdowns was from PostgreSQL 9.6-devel, so I'll have to make some additional changes before it will work on versions older than 9.5. I might not be able to get it working at all in PostgreSQL 9.1. If not, we might have to drop support for 9.1 with the next release, which I will probably call 1.1.0-alpha or something. 

I might not get around to fixing this today though.

**Comment by juliogonzalez** [comment]
Great!

If you remove 9.1 support, let me know so I can adjust the CI.

For this kind of experimental commits, maybe it would be better to use a branch. I can configure the CI so you can launch tests against branches other than master :-)

**Comment by GeoffMontee** [comment]
> For this kind of experimental commits, maybe it would be better to use a branch. I can configure the CI so you can launch tests against branches other than master :-)

Oh, nice! I'll try that next time I'm experimenting with something. Thanks!

I was able to get it to compile on PostgreSQL 9.4 without warnings. Now I'll continue working my way down from there.

**Comment by GeoffMontee** [comment]
This has been fixed for all versions except 9.1, and I'm removing support for 9.1 instead of fixing it, as mentioned in #69.
