### ISSUE TITLE
Remove support for PostgreSQL 9.1

### ISSUE THREAD

**Issue by GeoffMontee** [tds-fdw/tds_fdw#69]
I'm removing support for PostgreSQL 9.1.

I just removed some old 9.1-specific code here: https://github.com/tds-fdw/tds_fdw/commit/9affd7746299378d0124c262264ee3d59b719694

@juliogonzalez,

Can you please configure Jenkins to stop testing tds_fdw against 9.1 when you have a chance?

**Comment by juliogonzalez** [comment]
Done: https://jenkins.juliogonzalez.es/job/tds_fdw-build/186/

**Comment by GeoffMontee** [comment]
Thanks!
