### ISSUE TITLE
Implement IMPORT FOREIGN SCHEMA

### ISSUE THREAD

**Issue by GeoffMontee** [tds-fdw/tds_fdw#75]
PostgreSQL 9.5 adds IMPORT FOREIGN SCHEMA, but this is not yet implemented in tds_fdw.

http://www.postgresql.org/docs/9.5/static/sql-importforeignschema.html

http://blog.2ndquadrant.com/postgresql-9-5-import-foreign-schema/

**Comment by TwentyOneSolutions** [comment]
+1

This will be a great feature to have

**Comment by denishpatel** [comment]
is anyone working on it?

**Comment by GeoffMontee** [comment]
Not at the moment. If anyone else would like to try implementing it, pull requests would be most welcome.

**Comment by GeoffMontee** [comment]
@select-artur contributed a patch that implements IMPORT FOREIGN SCHEMA. It has been merged into master if anyone would like to test it.

**Comment by calebthompson** [comment]
@GeoffMontee I was able to import my (extensive) schema yesterday. I didn't get to verify everything but it looked pretty good.

**Comment by GeoffMontee** [comment]
Awesome! I'm glad to hear that it seemed to work pretty well for you, @calebthompson.

**Comment by JesseAwhere** [comment]
Please remove the second link in your initial comment. That site is compromised and it has a big scareware fake infected PC page.

**Comment by juliogonzalez** [comment]
Checked, the link was not working anymore.

**Comment by mbanck** [comment]
Should this issue not be closed as `IMPORT FOREIGN SERVER` has been implemented for a long time, or are there still loose ends (missing Sybase support? Though I think that was also added https://github.com/tds-fdw/tds_fdw/commit/f062f963ef86ce7d1e76b9387645daab0d4aa10f)

**Comment by GeoffMontee** [comment]
Thanks, @mbanck. I will close this one.
