### ISSUE TITLE
Cannot read data from tables

### ISSUE THREAD

**Issue by Smtgr14** [tds-fdw/tds_fdw#77]
When using tds_fdw version 2.0.0alpha.1 (as reported by \dx) in PostgreSQL 9.5,
I created a foreign table named "cisco_utc_time". It is populated with one row from the query:
"SELECT CONVERT(VARCHAR(19), GETUTCDATE(),120) AS server_time"
(I use this to calculate time offsets as the server drifts a bit throughout the day.)
This query runs fine, but when I build a foreign table that mimic a table on the same server, I get "ERROR: BB-Library error: DB #: 4145, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msq: (null), Level: 15"

This is a foreign table copied from a server running an older version of tds_fdw and Postgresql and it works just fine. I've copied the settings exactly from the old server but it seems to fail. Any ideas?

I also tried to use the latest stable tds_fdw but PostgreSQL reports the library is for 9.4 and cannot be used.

**Comment by GeoffMontee** [comment]
Can you please provide your `CREATE FOREIGN TABLE` statement?

Are you using the `query` option? If so, you are probably running into issue #72. That is fixed in master, but I haven't packaged it up in a release yet.

**Comment by Smtgr14** [comment]
Failing foreign table:
`CREATE FOREIGN TABLE cisco_person
   (personid integer ,
    firstname character(32) ,
    lastname character(32) ,
    loginname character(32) ,
    loginnameshadow character(32) ,
    password character(32) ,
    passwordchangerequired smallint ,
    passwordlastchangedtime character(32) ,
    loginenabled character(1) ,
    description character(255) ,
    deleted character(1) ,
    changestamp integer )
   SERVER ga_awdb
   OPTIONS (row_estimate_method 'execute', table 'dbo.Person');
ALTER FOREIGN TABLE cisco_person
  OWNER TO sinman;`

Working One:
`CREATE FOREIGN TABLE cisco_utc_time
   (server_time timestamp without time zone )
   SERVER ga_awdb
   OPTIONS (query 'SELECT CONVERT(VARCHAR(19), GETUTCDATE(),120) AS server_time', row_estimate_method 'execute');
ALTER FOREIGN TABLE cisco_utc_time
  OWNER TO sinman;`

**Comment by GeoffMontee** [comment]
Can you please set the `msg_handler` server option to `notice` for your foreign server, then try querying the table again, and then can you please provide the output?

e.g.:

```
ALTER SERVER ga_awdb 
   OPTIONS (ADD msg_handler 'notice');
```

**Comment by Smtgr14** [comment]
sydyk=# SELECT * FROM cisco_person;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'ga_awdb'., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 207, Msg state: 1, Msg: Invalid column name 'personid'., Server: NOVAHDS01, Process: , Line: 1, Level: 16
ERROR:  DB-Library error: DB #: 207, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 16
sydyk=#

**Comment by GeoffMontee** [comment]
It looks like the `dbo.Person` table doesn't have a column named `personid`:

```
NOTICE: DB-Library notice: Msg #: 207, Msg state: 1, Msg: Invalid column name 'personid'., Server: NOVAHDS01, Process: , Line: 1, Level: 16
```

What's the definition of the `dbo.Person` table in SQL Server?

**Comment by Smtgr14** [comment]
I've modified the foreign table definition. The field names are supposed to be camel case. Now when the query runs, I get all the columns but they are blank. After exiting the result view (in psql), I get these errors:

`sydyk=# SELECT * FROM cisco_person;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'ga_awdb'., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'ga_awdb'., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: NOVAHDS01, Process: , Line: 1, Level: 0
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Could not match local column PersonID with column from foreign table
WARNING:  Table definition mismatch: Could not match local column FirstName with column from foreign table
WARNING:  Table definition mismatch: Could not match local column LastName with column from foreign table
WARNING:  Table definition mismatch: Could not match local column LoginName with column from foreign table
WARNING:  Table definition mismatch: Could not match local column LoginNameShadow with column from foreign table
WARNING:  Table definition mismatch: Could not match local column Password with column from foreign table
WARNING:  Table definition mismatch: Could not match local column PasswordChangeRequired with column from foreign table
WARNING:  Table definition mismatch: Could not match local column PasswordLastChangedTime with column from foreign table
WARNING:  Table definition mismatch: Could not match local column LoginEnabled with column from foreign table
WARNING:  Table definition mismatch: Could not match local column Description with column from foreign table
WARNING:  Table definition mismatch: Could not match local column Deleted with column from foreign table
WARNING:  Table definition mismatch: Could not match local column Changestamp with column from foreign table`

**Comment by GeoffMontee** [comment]
Can you please provide the new `CREATE FOREIGN TABLE` statement that you used as well as the `CREATE TABLE` statement for the table on SQL Server?

**Comment by Smtgr14** [comment]
Foreign Table:

CREATE FOREIGN TABLE cisco_person
   ("PersonID" integer ,
    "FirstName" character(32) ,
    "LastName" character(32) ,
    "LoginName" character(32) ,
    "LoginNameShadow" character(32) ,
    "Password" character(32) ,
    "PasswordChangeRequired" smallint ,
    "PasswordLastChangedTime" character(32) ,
    "LoginEnabled" character(1) ,
    "Description" character(255) ,
    "Deleted" character(1) ,
    "Changestamp" integer )
   SERVER ga_awdb
   OPTIONS (row_estimate_method 'execute', table 'dbo.Person');
ALTER FOREIGN TABLE cisco_person
  OWNER TO sinman;


I cannot provide the CREATE TABLE on the SQL server (due to access restrictions), but I have this...
https://drive.google.com/open?id=0BwYYA-ZOQl9Iek5NV1locUxuV1g1YUtUSXoxV2tJV0NCYXpj

**Comment by GeoffMontee** [comment]
Based on the warnings you are seeing like this:

```
WARNING: Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
```

It looks like tds_fdw thinks the column names in the result set are empty strings. I'll have to look into this.

You can most likely get it to work by disabling `match_column_names` for the foreign table, but that will also disable WHERE clause and column push-downs, so that may also hurt performance. e.g.:

```
ALTER FOREIGN TABLE cisco_person
   OPTIONS (ADD match_column_names '0');
```

**Comment by Smtgr14** [comment]
And now it works, albeit slowly. Fabulous. Thank you.
With regards to pushdowns, that's unfortunate but most of the tables will be materialized into views. cisco_person is just a table that lists users who con use our phone system. Since it changes only when IT get around to it, a nightly refresh should be sufficient in the interim.

**Comment by GeoffMontee** [comment]
Awesome! I'm glad to hear it's working now.

Hopefully I can determine what is causing column name issue that you are seeing soon, so you don't have to disable pushdowns in order to use the table.

**Comment by GeoffMontee** [comment]
It seems as though quoted column names confuse FreeTDS.

For example, let's say that I have this table in MS SQL Server:

```
CREATE TABLE dbo.uppercase_column_name (
	id int,
	STRING varchar(50)
);

INSERT INTO dbo.uppercase_column_name VALUES (1, 'str1');
```

When I create the foreign table like this in PostgreSQL:

```
CREATE FOREIGN TABLE uppercase_column_name (
	id int,
	"STRING" varchar(50)
)
SERVER mssql_svr
OPTIONS (row_estimate_method 'execute', table 'dbo.uppercase_column_name');
```

I can see that tds_fdw sends the following query to the foreign server:

```
SELECT id, "STRING" FROM dbo.uppercase_column_name
```

But the name of the "STRING" column seems to be the empty string in the results:

```
postgres=# SELECT * FROM uppercase_column_name;
WARNING:  Table definition mismatch: Foreign source has column named , but target table does not. Column will be ignored.
WARNING:  Table definition mismatch: Could not match local column STRING with column from foreign table
 id | STRING
----+--------
  1 |
(1 row)
```

I'm not sure if this is a tds_fdw bug or a FreeTDS bug. It looks like tds_fdw is not getting the correct column name from FreeTDS when a column's name is quoted.

**Comment by GeoffMontee** [comment]
It looks like quotes around the column name are added here: https://github.com/tds-fdw/tds_fdw/blob/209fad0099505f0b238b3dd424b91ac3946ed959/src/deparse.c#L1094

If I remove the call to `quote_identifier` there, this does make things work. However, I wonder if that could break other tables that might have strange characters in some of the column names.

**Comment by GeoffMontee** [comment]
It seems to work if I change tds_fdw to use SQL Server's bracket quoting, so that it sends a query that looks like this:

```
SELECT [id], [STRING] FROM dbo.uppercase_column_name
```

Sybase also supports this syntax, so I should probably change tds_Fdw to use bracket quoting instead of double quotes: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc32300.1550/html/sqlug/X86464.htm

**Comment by GeoffMontee** [comment]
This should be fixed in the latest commit: https://github.com/tds-fdw/tds_fdw/commit/6404b95ff983a4d88357213f6fe49e762328a0b4

**Comment by Smtgr14** [comment]
Are you saying that using "ColumnName" in the foreign table definition should now match properly so I can drop `OPTION(match_column_names '0')` ?

**Comment by GeoffMontee** [comment]
> Are you saying that using "ColumnName" in the foreign table definition should now match properly so I can drop OPTION(match_column_names '0') ?

Yep, exactly. Now that tds_fdw uses bracket quoting, column names should match properly. You'll have to recompile and reinstall tds_fdw from the latest commit.

**Comment by Smtgr14** [comment]
I went and dropped the option from the foreign table from earlier. No errors. I assume everything is perfect. I then proceeded to drop the option from everywhere else. No complaints from anything. Thanks for the assistance and prompt fixes.
Guess this can be closed now.

**Comment by GeoffMontee** [comment]
Awesome! I'm glad to hear that it's working now. Please let me know if you have any other issues.
