### ISSUE TITLE
make install fails on CentOs 6.5 64 bits - Postgresql 9.3

### ISSUE THREAD

**Issue by vitormm** [tds-fdw/tds_fdw#8]
Hi,
I am trying to install tds_fdw extension on CentOs 6.5 and postgresql 9.3, but make fails at this step: PATH=/usr/pgsql-9.2/bin:$PATH make USE_PGXS=1 install  (https://github.com/GeoffMontee/tds_fdw#clone-and-build-1)

When I tried to create tds_fdw extension, the following error occurred: 

postgres=# CREATE EXTENSION tds_fdw;
ERROR:  could not access file "$libdir/tds_fdw": No such file or directory

Could you help? 
I installed Postgresl 9.3 from official repo.

Thanks!
Vitor

**Comment by binekkk** [comment]
i have the same problem on WINDOWS.
Do you have windows version? I just testet oracle_fdw and it wast copy&paste install....
Please answer,
Regards!

**Comment by GeoffMontee** [comment]
Hi @binekkk,

I haven't tried compiling under Windows, but you will also need a DB-Library implementation there too. The FreeTDS documentation lists [several ways to build FreeTDS on Windows](http://www.freetds.org/userguide/osissues.htm#WINDOWS).
